services:
  lmpvc_ros2_demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: lmpvc_ros2_cpu
    environment:
      - PULSE_SERVER=tcp:127.0.0.1:5050
    command: echo "Use 'docker compose run lmpvc_ros2_demo bash' to run the container"
    network_mode: host
    ipc: host
    pid: host
    restart: always
    volumes:
      - type: volume
        source: lmpvc_demo_build
        target: /lmpvc_ros2_ws
      - type: bind
        source: ./src
        target: /lmpvc_ros2_ws/src

volumes:
  lmpvc_demo_build: