services:
  lmpvc_ros2:
    build:
      context: .
      dockerfile: Dockerfile-cuda
    image: lmpvc_ros2_cuda
    runtime: nvidia
    environment:
      - PULSE_SERVER=tcp:127.0.0.1:5050
    command: echo "LMPVC container started!"
    network_mode: host
    ipc: host
    pid: host
    restart: always
    volumes:
      - type: volume
        source: lmpvc_build
        target: /lmpvc_ros2_ws
      - type: bind
        source: ./src
        target: /lmpvc_ros2_ws/src

volumes:
  lmpvc_build: